ci/kvm: retry helm installation
We've been hitting some server errors when attempting to install helm which have been
causing VMs to fail provisioning. Attempt to make this more robust by attempting up to
5 times before giving up.

Signed-off-by: William Findlay <will@isovalent.com>

diff --git a/.github/workflows/kvm-e2e-tests.yaml b/.github/workflows/kvm-e2e-tests.yaml
--- a/.github/workflows/kvm-e2e-tests.yaml
+++ b/.github/workflows/kvm-e2e-tests.yaml
@@ -124,7 +124,13 @@ jobs:
             cd /host/hubble-fgs
 
             mv /host/cilium /bin/cilium
-            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
+            for i in {1..5}; do
+              curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash && break || sleep 60
+              if [ \$i -eq 5 ]; then
+                echo "Failed to install Helm after 5 tries"
+                exit 1 
+              fi
+            done
 
       - name: Pull Docker Images
         run: |
