ci: move gofmt and module vendoring checks to static checks
These are static checks and don't really belong with go tests, so let's move them into the
static checks job.

Signed-off-by: William Findlay <will@isovalent.com>

diff --git a/.github/workflows/static-checks.yaml b/.github/workflows/static-checks.yaml
--- a/.github/workflows/static-checks.yaml
+++ b/.github/workflows/static-checks.yaml
@@ -35,17 +35,27 @@ jobs:
           skip-go-installation: true
           skip-pkg-cache: true
           skip-build-cache: true
-      - name: Build clang format Docker image
+      - name: Check gofmt formatting
+        run: |
+          go fmt ./...
+          git diff --exit-code || (echo "gofmt checks failed. Please run 'go -w fmt ./...', and submit your changes"; exit 1)
+      - name: Check module vendoring
+        run: |
+          go mod tidy
+          go mod vendor
+          go mod verify
+          test -z "$(git status --porcelain)" || (echo "Module vendoring checks failed. Please run 'go mod tidy && go mod vendor && go mod verify', and submit your changes"; exit 1)
+      - name: Build clang-format Docker image
         run: |
           docker build -f Dockerfile.clang-format -t "isovalent/clang-format:latest" .
       - name: Verify clang-format on BPF code
         id: clang_format
         run: |
-          set -e -o pipefail
+          set -o pipefail
           find bpf -name '*.c' -o -name '*.h' -not -path 'bpf/include/vmlinux.h' \
             -not -path 'bpf/include/api.h' -not -path 'bpf/libbpf/*' | xargs -n 1000 \
             docker run -v $(realpath .):/fgs "isovalent/clang-format:latest" --Werror -n -style=file
           if [ $? != 0 ]; then
-            echo "clang-format checks failed. Please run `make format` and try again."
+            echo "clang-format checks failed. Please run 'make format' and submit your changes."; exit 1
           fi
 
