workflows: split static checks to parallelize jobs
EE port of cilium/tetragon@e99f864dffa368ccb3043179d1f9486282809192

Signed-off-by: Mahe Tardy <mahe.tardy@gmail.com>

diff --git a/.github/workflows/static-checks.yaml b/.github/workflows/static-checks.yaml
--- a/.github/workflows/static-checks.yaml
+++ b/.github/workflows/static-checks.yaml
@@ -9,22 +9,20 @@ on:
     - "**.md"
 
 jobs:
-  static-checks:
+  golangci-lint:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
-        with:
-          submodules: true
+      - name: Checkout
+        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+
       - name: Install Go
         uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
         with:
           # renovate: datasource=golang-version depName=go
           go-version: '1.20.7'
-      - name: Install required libs
-        run: |
-          sudo apt-get -y install libelf-dev libz-dev build-essential
-      - name: Run static checks
-        uses: golangci/golangci-lint-action@639cd343e1d3b897ff35927a75193d57cfcba299 # v3
+
+      - name: Run golangci-lint
+        uses: golangci/golangci-lint-action@639cd343e1d3b897ff35927a75193d57cfcba299 # v3.6.0
         with:
           # renovate: datasource=docker depName=docker.io/golangci/golangci-lint
           version: v1.53.3
@@ -32,24 +30,28 @@ jobs:
           only-new-issues: false
           skip-pkg-cache: true
           skip-build-cache: true
+
+  format:
+    runs-on: ubuntu-latest 
+    steps:
+      - name: Checkout
+        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+
+      - name: Install Go
+        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
+        with:
+          # renovate: datasource=golang-version depName=go
+          go-version: '1.20.6'
+
       - name: Check gofmt formatting
-        if: success() || failure()
         run: |
           go fmt ./...
           git diff --exit-code || (echo "gofmt checks failed. Please run 'go -w fmt ./...', and submit your changes"; exit 1)
-      - name: Check module vendoring
-        if: success() || failure()
-        run: |
-          go mod tidy -compat=1.17
-          go mod vendor
-          go mod verify
-          test -z "$(git status --porcelain)" || (echo "Module vendoring checks failed. Please run 'make vendor', and submit your changes"; exit 1)
+
       - name: Build clang-format Docker image
-        if: success() || failure()
-        run: |
-          docker build -f Dockerfile.clang-format -t "isovalent/clang-format:latest" .
+        run: docker build -f Dockerfile.clang-format -t "isovalent/clang-format:latest" .
+
       - name: Verify clang-format on BPF code
-        if: success() || failure()
         id: clang_format
         run: |
           set -o pipefail
@@ -60,6 +62,22 @@ jobs:
           if [ $? != 0 ]; then
             echo "clang-format checks failed. Please run 'make format' and submit your changes."; exit 1
           fi
-      - name: Build Tarball
+
+  vendoring:
+    runs-on: ubuntu-latest 
+    steps:
+      - name: Checkout
+        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+
+      - name: Install Go
+        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
+        with:
+          # renovate: datasource=golang-version depName=go
+          go-version: '1.20.6'
+
+      - name: Check module vendoring
         run: |
-          make tarball
+          make vendor
+          echo "git status --porcelain:" `git status --porcelain`
+          test -z "$(git status --porcelain)" || (echo "Module vendoring checks failed. Please run 'make vendor', and submit your changes"; exit 1)
+
